import { MD3LightTheme } from "react-native-paper";
import themeFonts from "./fonts";

export const myTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#805611",
    surfaceTint: "#805611",
    onPrimary: "#FFFFFF",
    primaryContainer: "#FFDDB4",
    onPrimaryContainer: "#633F00",
    secondary: "#705B40",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#FBDEBC",
    onSecondaryContainer: "#56432B",
    tertiary: "#52643F",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#D5EABB",
    onTertiaryContainer: "#3B4C29",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#93000A",
    background: "#FFF8F4",
    onBackground: "#211B13",
    surface: "#FFF8F4",
    onSurface: "#211B13",
    surfaceVariant: "#F0E0D0",
    onSurfaceVariant: "#4F4539",
    outline: "#817567",
    outlineVariant: "#D3C4B4",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#362F27",
    inverseOnSurface: "#FCEFE2",
    inversePrimary: "#F5BC6F",
    primaryFixed: "#FFDDB4",
    onPrimaryFixed: "#291800",
    primaryFixedDim: "#F5BC6F",
    onPrimaryFixedVariant: "#633F00",
    secondaryFixed: "#FBDEBC",
    onSecondaryFixed: "#271904",
    secondaryFixedDim: "#DEC2A1",
    onSecondaryFixedVariant: "#56432B",
    tertiaryFixed: "#D5EABB",
    onTertiaryFixed: "#101F03",
    tertiaryFixedDim: "#B9CDA0",
    onTertiaryFixedVariant: "#3B4C29",
    surfaceDim: "#E4D8CC",
    surfaceBright: "#FFF8F4",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#FFF1E5",
    surfaceContainer: "#F9ECDF",
    surfaceContainerHigh: "#F3E6DA",
    surfaceContainerHighest: "#EDE0D4",
  },

  fonts: themeFonts,
};

export default myTheme;
